/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package prometheustest;

import io.prometheus.client.CollectorRegistry;
import io.prometheus.client.Gauge;
import io.prometheus.client.Histogram;
import io.prometheus.client.Summary;
import io.prometheus.client.exporter.HTTPServer;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.net.InetSocketAddress;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.ForkJoinPool;
import java.util.concurrent.RecursiveTask;
import java.util.function.Consumer;

public class App {
    public String getGreeting() {
        return "App:Hello World!";
    }

    public static void main(String[] args) throws InterruptedException {
        System.setProperty("java.util.concurrent.ForkJoinPool.common.parallelism", "60");
        AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext(PrometheusConfig1.class);
        var registry = context.getBean(CollectorRegistry.class);
        System.out.println(new App().getGreeting());

        var summary = new Summary.Builder()
                .name("mySummary")
                .help("mySummary desc")
                .quantile(0.0, 0.0001)
                .quantile(0.25, 0.0001)
                .quantile(0.5, 0.0001)
                .quantile(0.75, 0.0001)
                .create();

        var histo = new Histogram.Builder()
                .name("myHisto")
                .help("myHisto desc")
                .create();

        var counter = new Gauge.Builder()
                .name("myGauge")
                .help("myGauge desc")
                .create();


        registry.register(summary);
        registry.register(histo);
        registry.register(counter);
        var start = System.currentTimeMillis();
        //var report = new SummaryReporter(summary); // n=30, 160 sec
        var report = new SummaryThreadReporter(summary); // n=30, 164 sec
        //var report = new GaugeThreadReporter(counter); // 28s, n=47 - 60sec
        //var report = new HistoThreadReporter(histo); // 30, 0.5 SEC
        var task = new FibonacciTask(15, report); // 45
        var newPool  = new ForkJoinPool(60);

        //var task = new FibonacciTask(5, null);  // n=45 20000ms, n=47 53727ms
        System.out.println("number of parallellism: " + ForkJoinPool.commonPool().getParallelism());
        newPool.invoke(task);

        System.out.println("Duration>>>>>>>>>>>: " + (System.currentTimeMillis() - start));
        Thread.sleep(100000);
    }


    static class FibonacciTask extends RecursiveTask<Integer> {
        private final int n;
        private Consumer<Integer> summary;

        public FibonacciTask(int n, Consumer<Integer> consumer) {
            this.n = n;
            this.summary = consumer;
        }

        @Override
        protected Integer compute() {
            if (n <= 1) {
                return n;
            }
            if (summary != null)
                summary.accept(n);

            FibonacciTask fib1 = new FibonacciTask(n - 1, summary);
            fib1.fork();

            FibonacciTask fib2 = new FibonacciTask(n - 2, summary);
            return fib2.compute() + fib1.join();
        }

    }


    /**
     * # HELP mySummary mySummary desc
     * # TYPE mySummary summary
     * mySummary_count 1.836311902E9
     * mySummary_sum 6.643838831E9
     * # HELP mySummary_created mySummary desc
     * # TYPE mySummary_created gauge
     * mySummary_created 1.69868041756E9
     */
    static class SummaryReporter implements Consumer<Integer> {

        private Summary summary;

        public SummaryReporter(Summary summary) {
            this.summary = summary;
        }

        @Override
        public void accept(Integer integer) {
            summary.observe(integer);
        }
    }

    static class HistoThreadReporter implements Consumer<Integer> {

        private Histogram hist;
        private ExecutorService service = Executors.newFixedThreadPool(1);

        public HistoThreadReporter(Histogram histogram) {
            this.hist = histogram;
        }

        @Override
        public void accept(Integer integer) {
            hist.observe(integer);
            //service.submit(() -> hist.observe(integer));
        }
    }

    static class SummaryThreadReporter implements Consumer<Integer> {

        private Summary hist;
        private ExecutorService service = Executors.newFixedThreadPool(1);

        public SummaryThreadReporter(Summary histogram) {
            this.hist = histogram;
        }

        @Override
        public void accept(Integer integer) {
            hist.observe(integer);
            //service.submit(() -> hist.observe(integer));
        }
    }

    static class GaugeThreadReporter implements Consumer<Integer> {

        private Gauge gauge;
        private ExecutorService service = Executors.newFixedThreadPool(1);

        public GaugeThreadReporter(Gauge gauge) {
            this.gauge = gauge;
        }

        @Override
        public void accept(Integer integer) {
            gauge.inc();
            //service.submit(() -> hist.observe(integer));
        }
    }


    @Configuration
    public static class PrometheusConfig1 {

        @Bean
        public CollectorRegistry prometheusMeterRegistry() {
            return new CollectorRegistry();
        }

        @Bean
        public HTTPServer httpServer() throws Exception {
            var inetAddress = new InetSocketAddress("localhost", 9191);
            var result = new HTTPServer(inetAddress, prometheusMeterRegistry());
            return result;
        }


    }
}